---
title: "Inference for population means"
author: "Pulong Ma"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(root.dir="~/Documents/Teaching/STAT475_575/Fall2024/Data/")

library(ggplot2)
```

# Iris data
```{r}
data(iris)
head(iris)
```

# Sweet data 
```{r}
setwd("~/Documents/Teaching/STAT475_575/Fall2024/Data/")
sweat<-read.table("./sweat.dat",
           header=F, col.names=c("subject", "x1", "x2", "x3"))
head(sweat)

## Compute mean and covariance 
xbar = colMeans(sweat[ ,2:4])
print(xbar)

xvar = var(sweat[ ,2:4])
print(xvar)

## Q-Q plot
layout(matrix(1:4, nc=2))
sapply(colnames(sweat[ ,2:4]), 
       function(x){
         qqnorm(sweat[[x]], main="x")
         qqline(sweat[[x]])
       })

## Compute Shapiro-Wilk statistic
sapply(colnames(sweat[ ,2:4]), function(x) {
               shapiro.test(sweat[[x]]) } )

## Test for multivariate normality
library(mvShapiroTest)
mvShapiro.Test(as.matrix(sweat[ , 2:4]))

```

## Compute Hotelling statistic
```{r}
#install.packages("DescTools")
library(DescTools)
HotellingsT2Test(sweat[ ,2:4], mu=c(4, 50, 10))

```

## Confidence region
```{r, include=FALSE}
confint.region = function(x, alpha=0.95){
  p = ncol(x)
  n = nrow(x)
  xbar = colMeans(x)
  S = var(x)
  theta = seq(0, 2*pi, length=100)
  L = t(chol(S))
  
  polygon = xbar + 
    sqrt(p*(n-1)/(n*(n-p)) * qf(1-alpha, p, n-p)) * L %*% rbind(cos(theta), sin(theta) )
  
  return(t(polygon))
}
```

```{r, include=FALSE}
x <- matrix(c(-0.9,2.4,-1.4,2.9,2.0,0.2,0.7,1.0,-0.5,-1.0),ncol=2)

plot(confint.region(x), type="l")
points(x)
```

# Dog Anesthetics
```{r}
setwd("~/Documents/Teaching/STAT475_575/Fall2024/Data/")

dogdat<-read.table("dogs.dat",
            header=F, col.names=c("dog", "x1", "x2", "x3", "x4"))
head(dogdat)

#  Display a scatterplot matrix

pairs(dogdat[ , 2:5], panel=function(x, y, ...){points(x, y, ...)
          abline(lm(y ~ x), col="black")}, cex=1.5)
					
library(GGally)
ggpairs(dogdat[ , 2:5])
```

## Hotelling T-squared test
```{r}
# First enter the matrix of contrast coefficients.
C<-matrix( c(1, -1, 1, -1, -1, -1, 1, 1, -1, 1, 1, -1), 
		      nrow=3, ncol=4, byrow=T)
C

# Compute values of the contrasts from the four
# measurements taken on each dog.
newdat <- as.matrix(dogdat[ , 2:5])%*%t(C)
head(newdat)

#  Create a scatterplot of the contrast values
pairs(newdat)
```

##  Check each contrast for a normal distribution
```{r}
par(mfrow=c(2,2),pch=1)		
for (i in 1:3){
  qqnorm(newdat[,i],  main="Normal Q-Q Plot") }
apply(newdat[ ,1:3],2,shapiro.test)
```

## Test for multivariate normality
```{r}
library(mvShapiroTest)
mvShapiro.Test(newdat)
```

## Compute T-square statistic and p-value
```{r}
#  Attach the library of functions from the DescTools
#  package.  The HotelinsT2Test function produces the
#  T-squared value converted to an F statistic.  This
#  prodcues the correct p-value
library(DescTools)
HotellingsT2Test(newdat, mu = c(0,0,0), test = "f")
```

## chi-square approximation to T-squared statistic
```{r}
#  This produces the value of the T-squared statistic, not
#  the f-value, but it does not produce the correct p-value.
#  This p-value is too small because it is based on a
#  chi-square approximatin to the test statistic.

HotellingsT2Test(newdat, mu = c(0,0,0), test = "chi")
```

## Compute simultaneous 95\% confidence intervals 
```{r}
# Calculate the intervals in two ways
# (1)Bonferroni- adjusted t-intervals, and (2) T2 intervals. 

TB.conf.int <- function (X, level=0.95)
{ 
  # Convert X to a matrix, if it is not a matrix already

    X <- as.matrix(X)

  # Set n to the number of observations, p to the number of variables.

    n <- nrow(X)
    p <- ncol(X)

  # Stop if arguments are invalid.

    if (!is.numeric(X))
    { stop("Data must be numeric")}

  if (n<p)
  { 
    stop("Must have at least as many observations as variables")
  }

  if (!is.numeric(level) || length(level)!=1 || level<=0 || level>=1)
  { stop("Confidence level must be between 0 and 1")}

 #  Create a matrix A in which each column represents
 #  a difference between two pairs of means
    np <- p*(p-1)/2
    A <- matrix( c(0), ncol=np, nrow=p)
    nc <-0
    for (i in 1:(p-1)) {
      for (j in 1:(p-i)) {
        A[i, nc+j] <- 1
        i
        j
        A[i+j, nc+j] <- -1
    } 
     nc <- nc+(p-i)
     }


## Create a matrix that will hold the confidence intervals.
CI <- matrix(NA,2,ncol(A))
rownames(CI) <- c("lower","upper")
colnames(CI) <- colnames(A)

CIB <- matrix(NA,2,ncol(A))
rownames(CIB) <- c("lower","upper")
colnames(CIB) <- colnames(A)

CIT <- matrix(NA,2,ncol(A))
rownames(CIT) <- c("lower","upper")
colnames(CIT) <- colnames(A)


## Find F distribution quantile for T-squared confidence intervals
F <- qf(level,p,n-p)


## Find t distribution percentile for Bonferroni confidence intervals

  alpha <- (1-level)/2/ncol(A)
  levelB <- 1-alpha
  tB <- qt(levelB, n-1)
  t <- qt(1-(1-level)/2, n-1)

  # Compute the sample covariance matrix of the original variables.

  C <- cov(X)

  # Find the confidence intervals for the specified linear combinations.

  for (i in 1:ncol(A))
  { 
    # Find the sample mean and variance of this linear combination.

    m <- mean (X %*% A[,i])
    v <- t(A[,i]) %*% C %*% A[,i]
  # Find the confidence interval for this difference.

    CI[1,i] <- m - sqrt((p*(n-1)/n/(n-p)) * F * v)
    CI[2,i] <- m + sqrt((p*(n-1)/n/(n-p)) * F * v)

    CIB[1,i] <- m - tB*sqrt(v/n)
    CIB[2,i] <- m + tB*sqrt(v/n)

    CIT[1,i] <- m - t*sqrt(v/n)
    CIT[2,i] <- m + t*sqrt(v/n)
  }

  # Return all the confidence intervals.

  cat("T-squared simultaneous confidence intervals: \n\n")
  print(CI)

  cat("\n\n Bonferroni simultaneous confidence intervals: \n\n")
  print(CIB)

  cat("\n\n One-at-a-Time t confidence intervals: \n\n")
  print(CIT)
}
```


```{r}
 TB.conf.int(dogdat[ ,2:5])

```